---
- name: Set up
  hosts: app
  become: true
  gather_facts: true
  roles:
    - common
  tags: [common]

- name: Tear down existing services
  hosts: "{{ cleanup_hosts | default('app') }}" # To override, use --extra-vars
  become: false
  gather_facts: false
  roles:
    - cleanup
  tags: [cleanup]

- name: Deploy db
  hosts: db
  become: false
  gather_facts: false
  roles:
    - role: db
    # - role: monitor
    # - role: logger
  tags: [deploy, mointor, logger, db]

- name: Deploy scalable api
  hosts: api
  become: false
  gather_facts: false
  roles:
    - role: api
    - role: lb
      lb_service: "{{ api_lb_service }}"
      lb_dest: "{{ api_lb_dest }}"
      lb_dest_cleanup: "{{ api_lb_dest_cleanup }}"
      lb_forward_port: "{{ api_lb_forward_port }}"
      lb_target: "{{ api_service }}"
      lb_target_dest: "{{ api_dest }}"
      lb_target_scale: "{{ api_scale }}"
    # - role: monitor
    # - role: logger
  tags: [deploy, monitor, logger, api]

- name: Deploy scalable web
  hosts: web
  become: false
  gather_facts: false
  roles:
    - role: web
    - role: lb
      lb_service: "{{ web_lb_service }}"
      lb_dest: "{{ web_lb_dest }}"
      lb_dest_cleanup: "{{ web_lb_dest_cleanup }}"
      lb_forward_port: "{{ web_lb_forward_port }}"
      lb_target: "{{ web_service }}"
      lb_target_dest: "{{ web_dest }}"
      lb_target_scale: "{{ web_scale }}"
    # - role: monitor
    # - role: logger
  tags: [deploy, monitor, logger, web]
