---
- name: Set up
  hosts: app
  become: true
  gather_facts: true
  roles:
    - common
  tags: [common]

- name: Tear down existing services
  hosts: "{{ cleanup_hosts | default('app') }}" # To override, use --extra-vars
  become: true
  gather_facts: false
  roles:
    - role: cleanup
      prune_everything: "{{ cleanup_prune_everything }}"
  tags: [cleanup]

- name: Deploy db
  hosts: db
  become: true
  gather_facts: false
  roles:
    - db
  tags: [deploy, db]

- name: Deploy api
  hosts: api
  become: true
  gather_facts: false
  roles:
    - role: api
    - role: lb
      lb_service: "{{ api_lb_service }}"
      lb_dest: "{{ api_lb_dest }}"
      lb_dest_cleanup: "{{ api_lb_dest_cleanup }}"
      lb_forward_port: "{{ api_lb_forward_port }}"
      lb_target: "{{ api_service }}"
      lb_target_dest: "{{ api_dest }}"
      lb_target_scale: "{{ api_scale }}"
  tags: [deploy, lb, api]

- name: Deploy web
  hosts: web
  become: true
  gather_facts: false
  roles:
    - role: web
    - role: lb
      lb_service: "{{ web_lb_service }}"
      lb_dest: "{{ web_lb_dest }}"
      lb_dest_cleanup: "{{ web_lb_dest_cleanup }}"
      lb_forward_port: "{{ web_lb_forward_port }}"
      lb_target: "{{ web_service }}"
      lb_target_dest: "{{ web_dest }}"
      lb_target_scale: "{{ web_scale }}"
  tags: [deploy, lb, web]

- name: Deploy monitors
  hosts: app
  become: true
  gather_facts: false
  roles:
    - monitor
  tags: [monitor]

- name: Deploy loggers
  hosts: app
  become: true
  gather_facts: false
  roles:
    - monitor
  tags: [monitor]
