---
- name: Create group {{ username }}
  ansible.builtin.group:
    name: "{{ username }}"

- name: Create user {{ username }}
  ansible.builtin.user:
    name: "{{ username }}"
    group: "{{ username }}"

- name: Uninstall old versions
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Allow apt to use repository over HTTPS
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture[ansible_architecture] }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure docker-group added user {{ username }}
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true

- name: Reset SSH connection to re-evaluate group membership
  ansible.builtin.meta: reset_connection
