---
- name: Create networks
  community.docker.docker_network:
    name: "{{ item }}"
  loop: "{{ web_networks }}"

- name: Create container
  community.docker.docker_container:
    name: "{{ web_name }}"
    hostname: "{{ web_name }}"
    restart_policy: unless-stopped
    image: "{{ web_image }}"
    networks:
      - name: "{{ item }}"
    ports:
      - 80:80
  loop: "{{ web_networks }}"
