---
- name: Remove directory {{ web_dest }}
  ansible.builtin.file:
    path: "{{ web_dest }}"
    state: absent
  when: web_dest_cleanup | default(false) | bool

- name: Create directory {{ web_dest }}
  ansible.builtin.file:
    path: "{{ web_dest }}"
    state: directory
    mode: "0755"

- name: Generate docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ web_dest }}/docker-compose.yml"
    mode: "0644"

- name: Create and start service {{ web_service }}
  community.docker.docker_compose:
    project_src: "{{ web_dest }}"
    state: present
    services:
      - "{{ web_service }}"
