server:
  log_level: info
  http_listen_port: 12345

metrics:
  global:
    scrape_interval: 30s
    external_labels:
      environment: test-server   
  configs:  
    - name: default
      scrape_configs:
        - job_name: agent
          static_configs:
            - targets: ['grafana-agent:12345']
        - job_name: 'node_exporter'
          static_configs:
          - targets: ['node_exporter:9100']
        - job_name: 'cadvisor'
          static_configs:
          - targets: ['cadvisor:8080']
      remote_write:
        - url: https://example.com/api/v1/write
          basic_auth:
            username: admin
            password: secret-password
